# File : .pep8speaks.yml

scanner:
    diff_only: True  # If True, errors caused by only the patch are shown

pycodestyle:
    max-line-length: 79
    ignore:  # Errors and warnings to ignore
        - E402,  # module level import not at top of file
        - E731,  # do not assign a lambda expression, use a def
        - W503   # line break before binary operator
