version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
  jobs:
    post_checkout:
      - (git --no-pager log --pretty="tformat:%s" -1 | grep -vqF "[skip-rtd]") || exit 183
    pre_install:
      - git update-index --assume-unchanged doc/conf.py ci/requirements/doc.yml

conda:
  environment: ci/requirements/doc.yml

sphinx:
  fail_on_warning: true

formats: []
