version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
  jobs:
    post_checkout:
      - git fetch --unshallow --tags  # to allow setuptools_scm to work properly
    pre_install:
      - git update-index --assume-unchanged doc/conf.py ci/requirements/doc.yml

conda:
  environment: ci/requirements/doc.yml

sphinx:
  fail_on_warning: true

formats: []
