version: 2

sphinx:
  configuration: doc/conf.py
  fail_on_warning: true

build:
  os: ubuntu-lts-latest
  jobs:
    create_environment:
      - asdf plugin add pixi
      - asdf install pixi latest
      - asdf global pixi latest
    post_checkout:
      - (git --no-pager log --pretty="tformat:%s" -1 | grep -vqF "[skip-rtd]") || exit 183
      - git fetch --unshallow || true
    pre_install:
      - git update-index --assume-unchanged doc/conf.py ci/requirements/doc.yml
    install:
      - pixi install -e doc

formats:
  - htmlzip
