linters:
  flake8:
    max-line-length: 79
    fixer: false
    ignore: I002
    # stickler doesn't support 'exclude' for flake8 properly, so we disable it
    # below with files.ignore:
    # https://github.com/markstory/lint-review/issues/184
files:
  ignore:
    - doc/**/*.py
