name: xarray-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cartopy
  - iris
  - matplotlib-base
  - nc-time-axis
  # - numba
  # - numbagg
  # - pint>=0.22
  - pooch
  - seaborn
  # - sparse
  - pip:
      - jax # no way to get cpu-only jaxlib from conda if gpu is present
