name: xarray-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - aiobotocore
  - array-api-strict<2.4
  - boto3
  - bottleneck
  - cartopy
  - cftime
  - dask-core
  - distributed
  - flox
  - fsspec
  - h5netcdf
  - h5py
  - hdf5
  - hypothesis
  - iris
  - lxml # Optional dep of pydap
  - matplotlib-base
  - nc-time-axis
  - netcdf4
  # - numba
  # - numbagg
  - numexpr
  - opt_einsum
    # - pint>=0.22
  - pooch
  - pre-commit
  - pyarrow # pandas raises a deprecation warning without this, breaking doctests
  - pydap
  - rasterio
  - scipy
  - seaborn
  # - sparse
  - toolz
  - types-colorama
  - types-docutils
  - types-psutil
  - types-Pygments
  - types-python-dateutil
  - types-pytz
  - types-PyYAML
  - types-setuptools
  - typing_extensions
  - zarr
  - pip:
      - jax # no way to get cpu-only jaxlib from conda if gpu is present
      - types-defusedxml
      - types-pexpect
