name: xarray-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  # - numba
  # - numbagg
  # - pint>=0.22
  # - sparse
  - pip:
      - jax # no way to get cpu-only jaxlib from conda if gpu is present
