blank_issues_enabled: true
contact_links:
  - name: Usage question
    url: https://stackoverflow.com/questions/tagged/python-xarray
    about: "Post a question on Stack Overflow using the #python-xarray
    tag. These are regularly reviewed by xarray's maintainers, and questions which
    include a reproducible example will receive a response."