# import public API
from xarray.datatree_.datatree.datatree import DataTree
from xarray.datatree_.datatree.extensions import register_datatree_accessor
from xarray.datatree_.datatree.io import open_datatree
from xarray.datatree_.datatree.mapping import TreeIsomorphismError, map_over_subtree
from xarray.datatree_.datatree.treenode import InvalidTreeError, NotFoundInTreeError

try:
    # NOTE: the `_version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from xarray.datatree_.datatree._version import __version__
except ImportError:  # pragma: no cover
    # Local copy or not installed with setuptools
    __version__ = "999"

__all__ = (
    "DataTree",
    "open_datatree",
    "TreeIsomorphismError",
    "InvalidTreeError",
    "NotFoundInTreeError",
    "map_over_subtree",
    "register_datatree_accessor",
    "__version__",
)
