name: Cancel
on:
  workflow_run:
    workflows: ["CI", "CI Additional", "CI Upstream"]
    types:
      - requested
jobs:
  cancel:
    name: Cancel previous runs
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.8.0
      with:
        workflow_id: ${{ github.event.workflow.id }}
