name: "PR Labeler"
on:
  # ignore zizmor in this case, because the only thing we execute with PR write
  # permissions is actions/labeler (this is also the recommended setup of this action).
  # Either way, we only run this on the main repository.
  - pull_request_target # zizmor: ignore[dangerous-triggers]

permissions: {}

jobs:
  label:
    runs-on: ubuntu-latest
    if: github.repository == 'pydata/xarray'

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: false
